# Generated by Django 6.0.2 on 2026-02-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=50)),
                ('avatar_letter', models.CharField(max_length=2)),
                ('avatar_color', models.CharField(choices=[('purple', 'Purple'), ('pink', 'Pink'), ('green', 'Green'), ('gold', 'Gold'), ('blue', 'Blue')], default='purple', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('medical', 'Medical'), ('education', 'Education'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], default='image', max_length=10)),
                ('drive_file_id', models.CharField(blank=True, max_length=200)),
                ('drive_view_url', models.URLField(blank=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vault.familymember')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
